# Generated by Django - merge migration
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0073_collectiontemplate'),
        ('adventures', '0075_auditlog'),
        ('adventures', '0077_transportation_lodging_collections_m2m'),
    ]

    operations = [
    ]
